In [2]:
# call pandas
import pandas as pd # 'pd' is a nickname

In [4]:
from IPython.display import IFrame

In [5]:
wikiLink="https://en.wikipedia.org/wiki/LGBT_demographics_of_the_United_States"
IFrame(wikiLink, width=700, height=300)

In [6]:
WikiList2=pd.read_html(wikiLink,
                    header=0,
                    flavor='bs4',
                    attrs={'class': 'wikitable'})# very important

In [7]:
WikiList2[0]

,Pop. rank,% rank,State or territory,2015â€“2016 LGBT adult percentage estimate[7],2012 state total population estimate[8],2012 LGBT adult population estimate,2000 same-sex couple households[9],2010 same-sex couple households[10],2000 to 2010 couple households growth[9],2016 transgender adult percentage estimate[2]
0,1,9,California,4.8%,38041430,1338164,92138,98153,6.53%,0.76%
1,2,31,Texas,3.6%,26084481,579968,42912,46401,8.13%,0.66%
2,3,13,New York,4.5%,19570261,570388,46490,48932,4.05%,0.51%
3,4,21,Florida,4.2%,19317568,513849,41048,48496,18.15%,0.66%
4,5,15,Illinois,3.7%,12875255,362048,22887,23049,0.07%,0.51%
5,6,20,Ohio,3.8%,11544225,315592,18937,19684,3.95%,0.45%
6,7,14,Michigan,3.8%,9883360,285431,15368,14598,-5.0%,0.43%
7,8,22,Georgia,4.0%,9919945,263870,19288,21318,10.52%,0.75%
8,9,43,Pennsylvania,3.6%,12763536,262308,21166,22336,5.50%,0.44%
9,10,17,New Jersey,3.6%,8864590,249273,16604,16875,1.60%,0.44%
10,11,30,North Carolina,3.5%,9752073,244582,16198,18309,11.36%,0.60%
11,12,7,Massachusetts,4.9%,6646144,247247,17099,20256,18.46%,0.57%
12,13,10,Washington,4.6%,6897012,209670,15900,19003,19.51%,0.62%
13,14,12,Arizona,4.0%,6553255,194238,12332,15817,28.25%,0.62%
14,15,18,Indiana,4.1%,6537334,183829,10219,11074,8.37%,0.56%
15,16,36,Virginia,3.4%,8185867,180416,13802,14243,3.20%,0.55%
16,17,29,Missouri,3.4%,6021988,151032,9428,10557,10.70%,0.54%
17,18,28,Maryland,5.7%,5884563,147584,11243,12538,11.52%,0.49%
18,19,4,Oregon,4.9%,3899353,145212,8932,11773,31.80%,0.65%
19,20,11,Kentucky,3.3%,4380415,129836,7114,7195,1.13%,0.53%
20,21,47,Tennessee,3.1%,6456243,127526,10189,10898,6.95%,0.63%
21,22,33,Colorado,4.3%,5187582,126162,10045,12424,23.70%,0.53%
22,23,40,Wisconsin,3.4%,5726398,121858,8232,9179,10.32%,0.43%
23,24,35,Minnesota,4.0%,5379139,118556,9147,10207,11.60%,0.59%
24,25,32,Louisiana,3.9%,4601893,111918,8808,8076,-8.31%,0.60%
25,26,37,South Carolina,3.5%,4723723,104111,7609,7214,5.20%,0.58%
26,27,42,Alabama,3.0%,4822023,102613,8109,6582,-18.80%,0.61%
27,28,26,Oklahoma,3.5%,3814820,98575,5763,6134,6.44%,0.64%
28,29,8,Nevada,4.8%,2758931,88065,4973,7140,43.60%,0.61%
29,30,19,Kansas,3.1%,2885905,81152,3973,4009,0.09%,0.43%
30,31,23,Arkansas,3.0%,2949131,78441,4423,4226,-4.45%,0.60%
31,32,24,Connecticut,3.5%,3590347,92775,7386,7852,6.30%,0.44%
32,33,41,Iowa,3.2%,3074186,65419,3698,4093,10.70%,0.31%
33,34,48,Mississippi,3.2%,2984926,58982,4774,3484,-27.00%,0.61%
34,35,46,Utah,3.3%,2855287,58591,3360,5814,73.03%,0.36%
35,36,2,Hawaii,3.8%,1392313,53966,2389,3239,35.45%,0.78%
36,37,5,Maine,4.5%,1329192,48489,3394,3958,16.61%,0.50%
37,38,1,District of Columbia,8.6%,632323,63232,3678,4822,31.10%,2.77%
38,39,39,New Mexico,4.2%,2085538,45965,4496,5825,25.56%,0.75%
39,40,34,West Virginia,3.4%,1855413,43713,2916,2848,-2.33%,0.42%
40,41,44,Nebraska,3.6%,1855525,38075,2332,2356,0.01%,0.39%
41,42,16,New Hampshire,4.6%,1320718,31138,2703,3260,20.60%,0.43%
42,43,6,Rhode Island,4.0%,1050292,35920,2471,2785,12.71%,0.51%
43,44,45,Idaho,2.8%,1595728,32744,1873,2042,9.02%,0.41%
44,45,51,South Dakota,2%,833354,27867,826,714,-13.36%,0.34%
45,46,25,Delaware,4.7%,917092,23698,1868,2646,41.65%,0.64%
46,47,3,Vermont,5.3%,626011,23313,1933,2143,10.61%,0.59%
47,48,49,Montana,3.0%,1005141,19862,1218,1848,10.70%,0.34%
48,49,27,Alaska,3.0%,731449,24869,1180,1228,4.06%,0.49%
49,50,38,Wyoming,3.5%,576412,16716,807,657,-18.60%,0.32%
50,51,50,North Dakota,2.7%,699628,9040,703,559,-20.50%,0.30%
51,â€”,â€”,Total,3.8%,"Total population: 313,914,039 Adult population...",9083558,594391,646464,8.76%,0.58%

In [18]:
# Uploading CVS dataset
# use a function from pandas to read the cloud data into a Python object
gitCloudRepo='https://github.com/542CompThink/Deliverable1/raw/main/'
fileName="stateinfo1990.csv"

DFcsv=pd.read_csv(gitCloudRepo + fileName)

In [19]:
DFcsv

,STATEA,STATE,D0J001,D0J002,D0J003,D0J004,D0J005,D0J006,D0J007,D0J008,...,EIN003,EIN004,EIN005,EIP001,EIP002,EIP003,EIP004,EIP005,EIP006,EIP007
0,statefip,statename,Establishments: 1 to 4 employees,Establishments: 5 to 9 employees,Establishments: 10 to 19 employees,Establishments: 20 to 49 employees,Establishments: 50 to 99 employees,Establishments: 100 to 249 employees,Establishments: 250 to 499 employees,Establishments: 500 to 999 employees,...,"Civilian labor force, employed","Civilian labor force, unemployed",Not in labor force,Less than 9th grade,"9th grade to 12th grade, no diploma",High school graduate (includes equivalency),"Some college, no degree",Associate degree,Bachelor's degree,Graduate or professional degree
1,1,Alabama,45361,18382,11088,7296,2398,1390,372,166,...,1741794,128587,1208168,984391,750427,879291,575754,146281,281481,142177
2,2,Alaska,8618,2931,1782,938,272,172,43,12,...,245379,23587,99437,115048,55199,115419,107444,25525,50809,25981
3,4,Arizona,46342,17783,10890,7291,2413,1336,267,105,...,1603896,123902,1032252,782152,493922,712607,725084,173871,325610,161560
4,5,Arkansas,30089,10746,6238,3917,1295,750,227,100,...,994289,72079,722905,599609,417469,573732,323353,62267,143091,67144
5,6,California,403756,143313,93673,65659,22999,11830,2842,1002,...,13996309,996502,7523381,6643367,4146962,5111944,5254155,1650390,3052962,1523767
6,8,Colorado,55590,19009,10881,7245,2394,1283,267,85,...,1633281,99438,747375,622012,378866,656701,630944,161378,402917,190168
7,9,Connecticut,50694,18469,11652,7286,2519,1539,421,147,...,1692874,95819,812290,606886,433173,761085,458507,163137,393526,243686
8,10,Delaware,10006,3804,2434,1569,515,285,85,39,...,335147,13945,164472,125724,98739,167309,97523,30542,64555,33328
9,11,District Of Columbia,9481,3880,2851,2021,706,419,141,54,...,303994,23442,169654,105532,102513,107628,90212,14322,78581,71496
10,12,Florida,203692,72938,41868,26843,9410,5068,904,391,...,5810467,356769,4108146,2499498,2096556,3058818,2057552,682296,1133086,567478
11,13,Georgia,82561,32521,20179,13686,4698,2866,740,285,...,3090276,188102,1586868,1509414,1083182,1441697,896364,226718,566488,260325
12,15,Hawaii,15243,6064,3881,2619,878,467,93,41,...,529059,19288,253170,230671,122736,257019,181860,65150,117888,50885
13,16,Idaho,14725,5667,3324,1884,570,249,55,22,...,443703,29070,251533,234035,137164,212861,182644,50333,77768,31898
14,17,Illinois,143920,53706,35242,23944,8646,5171,1266,528,...,5417967,385040,2956318,2457206,1620806,2543940,1819579,490961,1101193,552153
15,18,Indiana,64843,27422,17132,11597,4048,2362,567,207,...,2628695,160143,1450553,1167920,870523,1534908,776201,212456,360095,224057
16,19,Iowa,39816,15190,9211,5615,1926,979,236,92,...,1340242,63641,725200,599339,323530,768930,412400,158653,227682,92992
17,20,Kansas,36385,13216,8031,5316,1719,885,187,72,...,1172214,57772,624994,515866,295302,589677,440806,98477,239238,110249
18,21,Kentucky,41612,16520,10076,6740,2305,1230,329,131,...,1563960,124354,1120564,1021547,603747,885255,476907,108448,209055,129996
19,22,Louisiana,46845,18430,11208,7247,2696,1364,323,117,...,1641614,175303,1269674,1118724,695620,958343,587428,94447,288167,143624
20,23,Maine,20220,6900,4045,2357,751,401,98,48,...,571842,40722,327902,253382,162388,342977,165972,61105,107482,48816
21,24,Maryland,58187,23834,16147,10485,3609,1904,449,156,...,2481342,111536,1096934,900885,671470,1049928,745587,182517,532886,342012
22,25,Massachusetts,83414,32010,20368,13417,4811,3003,802,315,...,3027950,218000,1547909,1078325,763573,1396471,867910,325344,746844,427284
23,26,Michigan,107851,44801,28194,18463,6319,3337,786,330,...,4166196,374341,2547860,1876856,1448737,2188046,1557027,443182,701768,379121
24,27,Minnesota,58315,22828,15034,9836,3444,1927,504,188,...,2192417,118919,1006440,929721,460048,1037098,699133,270496,467835,174530
25,28,Mississippi,29728,10711,6217,3790,1318,774,230,90,...,1028773,94712,768958,698144,478055,510474,354875,95103,163214,78940
26,29,Missouri,70933,25860,16042,10809,3651,2137,525,212,...,2367395,155388,1397932,1159611,751719,1255915,786460,170184,420521,204294
27,30,Montana,15097,4901,2826,1546,432,175,34,13,...,350723,26217,217905,176919,97810,191343,138844,31337,74900,29065
28,31,Nebraska,24209,9038,5303,3363,1067,533,133,72,...,772813,29326,377733,334102,180667,389754,273169,80973,141231,59008
29,32,Nevada,15631,6122,3962,2673,855,458,109,58,...,607437,40083,278172,217131,185517,291219,238948,52472,83870,41293
30,33,New Hampshire,18617,6761,3971,2419,833,470,109,50,...,574237,38108,241683,209175,134859,266458,166476,64046,126495,57112
31,34,New Jersey,121516,39888,25097,16538,5951,3605,940,337,...,3868698,235975,2001134,1504523,1120211,1868662,1032028,307991,905113,462168
32,35,New Mexico,19826,7344,4399,2770,824,418,72,36,...,629272,54888,414012,371421,217213,315428,239975,51449,117742,76820
33,36,New York,273896,84812,51993,34546,11638,6652,1852,799,...,8370718,618903,5161498,3619338,2753857,4061132,2465559,898457,1758236,1186469
34,37,North Carolina,88146,34083,20292,13442,4948,2803,818,382,...,3238414,163081,1683303,1470235,1125477,1501942,959843,324242,559176,231386
35,38,North Dakota,11075,3823,2183,1233,403,204,39,15,...,287558,16083,166930,165668,63924,127965,111065,45633,58403,18181
36,39,Ohio,125575,52823,33541,22290,8052,4568,1127,433,...,4931357,348638,3051110,2199241,1741532,2903952,1551187,412308,843456,411536
37,40,Oklahoma,42316,14821,8737,5673,1898,897,197,79,...,1369138,100931,899495,696228,489756,708923,539981,113452,253635,119780
38,41,Oregon,44568,16384,10143,6492,2076,1050,246,79,...,1319960,87183,781069,547164,378177,616619,561678,139274,267167,130403
39,42,Pennsylvania,147584,57296,35811,23411,8327,5010,1305,551,...,5434532,344795,3594879,2355961,1851351,3486100,1392837,474188,996005,528728
40,44,Rhode Island,15459,5349,3385,2217,738,415,100,39,...,487913,34690,271509,202301,162602,230154,141682,48017,99704,51963
41,45,South Carolina,42520,16872,9755,6448,2216,1275,413,169,...,1603425,94673,906860,833557,612317,779976,466738,152769,267371,118811
42,46,South Dakota,12042,3992,2373,1380,443,197,49,9,...,321891,13983,174920,178515,76082,165597,106253,36317,57149,21313
43,47,Tennessee,59862,22884,14303,9786,3442,2137,554,215,...,2250842,154235,1367388,1221396,825026,1124920,694262,147227,359948,171964
44,48,Texas,215009,79133,48450,32475,10762,6175,1550,586,...,7634279,584749,4306456,4314751,2540348,3166245,2781010,599253,1530893,673322
45,49,Utah,18779,7855,5006,3124,1019,572,139,56,...,736059,41389,369538,407924,219641,295198,340842,81885,146222,61639
46,50,Vermont,11783,3863,2259,1271,411,184,46,12,...,283146,17600,133125,114032,66842,145000,74847,29278,59593,31929
47,51,Virginia,77589,31462,20115,12635,4469,2391,650,248,...,3028362,142048,1504193,1315047,874835,1301592,970074,244546,676723,363602
48,53,Washington,72841,26264,16620,10612,3328,1682,373,121,...,2293961,139216,1243912,921266,581809,1023053,948628,278139,527835,221149
49,54,West Virginia,20806,7844,4601,2867,912,470,114,53,...,671085,71142,660868,467443,311108,494645,209299,51003,96372,57062
50,55,Wisconsin,63840,24977,15899,10585,3770,2141,585,241,...,2386439,130799,1210873,1060460,618763,1313671,703212,250651,409555,174822
51,56,Wyoming,8687,3015,1589,930,251,132,21,4,...,207868,13112,107439,98977,56167,105303,82515,21464,38305,15982

In [12]:
# columns present - add .to_list()
DFcsv.columns

Index(['STATEA', 'STATE', 'D0J001', 'D0J002', 'D0J003', 'D0J004', 'D0J005',
       'D0J006', 'D0J007', 'D0J008', 'D0J009', 'ET1001', 'EUW001', 'EUW002',
       'EUW003', 'EUY001', 'EUY002', 'EUY003', 'EUY004', 'EUY005', 'EIN002',
       'EIN003', 'EIN004', 'EIN005', 'EIP001', 'EIP002', 'EIP003', 'EIP004',
       'EIP005', 'EIP006', 'EIP007'],
      dtype='object')